//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainNotifier.IIS.WebApi.OpenLDBWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", ConfigurationName="OpenLDBWS.LDBServiceSoap")]
    public interface LDBServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (GetDepartureBoardRequest) of message GetDepartureBoardRequest does not match the default value (GetDepartureBoard)
        [System.ServiceModel.OperationContractAttribute(Action="http://thalesgroup.com/RTTI/2012-01-13/ldb/GetDepartureBoard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TrainNotifier.IIS.WebApi.OpenLDBWS.GetDepartureBoardResponse GetDepartureBoard(TrainNotifier.IIS.WebApi.OpenLDBWS.GetDepartureBoardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thalesgroup.com/RTTI/2012-01-13/ldb/GetDepartureBoard", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainNotifier.IIS.WebApi.OpenLDBWS.GetDepartureBoardResponse> GetDepartureBoardAsync(TrainNotifier.IIS.WebApi.OpenLDBWS.GetDepartureBoardRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetArrivalBoardRequest) of message GetArrivalBoardRequest does not match the default value (GetArrivalBoard)
        [System.ServiceModel.OperationContractAttribute(Action="http://thalesgroup.com/RTTI/2012-01-13/ldb/GetArrivalBoard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalBoardResponse GetArrivalBoard(TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalBoardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thalesgroup.com/RTTI/2012-01-13/ldb/GetArrivalBoard", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalBoardResponse> GetArrivalBoardAsync(TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalBoardRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetArrivalDepartureBoardRequest) of message GetArrivalDepartureBoardRequest does not match the default value (GetArrivalDepartureBoard)
        [System.ServiceModel.OperationContractAttribute(Action="http://thalesgroup.com/RTTI/2012-01-13/ldb/GetArrivalDepartureBoard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalDepartureBoardResponse GetArrivalDepartureBoard(TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalDepartureBoardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thalesgroup.com/RTTI/2012-01-13/ldb/GetArrivalDepartureBoard", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalDepartureBoardResponse> GetArrivalDepartureBoardAsync(TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalDepartureBoardRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetServiceDetailsRequest) of message GetServiceDetailsRequest does not match the default value (GetServiceDetails)
        [System.ServiceModel.OperationContractAttribute(Action="http://thalesgroup.com/RTTI/2012-01-13/ldb/GetServiceDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TrainNotifier.IIS.WebApi.OpenLDBWS.GetServiceDetailsResponse GetServiceDetails(TrainNotifier.IIS.WebApi.OpenLDBWS.GetServiceDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thalesgroup.com/RTTI/2012-01-13/ldb/GetServiceDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainNotifier.IIS.WebApi.OpenLDBWS.GetServiceDetailsResponse> GetServiceDetailsAsync(TrainNotifier.IIS.WebApi.OpenLDBWS.GetServiceDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2013-11-28/Token/types")]
    public partial class AccessToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TokenValue {
            get {
                return this.tokenValueField;
            }
            set {
                this.tokenValueField = value;
                this.RaisePropertyChanged("TokenValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2012-01-13/ldb/types")]
    public partial class CallingPoint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string locationNameField;
        
        private string crsField;
        
        private string stField;
        
        private string etField;
        
        private string atField;
        
        private string[] adhocAlertsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
                this.RaisePropertyChanged("locationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string crs {
            get {
                return this.crsField;
            }
            set {
                this.crsField = value;
                this.RaisePropertyChanged("crs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string st {
            get {
                return this.stField;
            }
            set {
                this.stField = value;
                this.RaisePropertyChanged("st");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string et {
            get {
                return this.etField;
            }
            set {
                this.etField = value;
                this.RaisePropertyChanged("et");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string at {
            get {
                return this.atField;
            }
            set {
                this.atField = value;
                this.RaisePropertyChanged("at");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("adhocAlertText")]
        public string[] adhocAlerts {
            get {
                return this.adhocAlertsField;
            }
            set {
                this.adhocAlertsField = value;
                this.RaisePropertyChanged("adhocAlerts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/types")]
    public partial class ArrayOfCallingPoints : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CallingPoint[] callingPointField;
        
        private ServiceType serviceTypeField;
        
        private bool serviceTypeFieldSpecified;
        
        private bool serviceChangeRequiredField;
        
        private bool serviceChangeRequiredFieldSpecified;
        
        private bool assocIsCancelledField;
        
        private bool assocIsCancelledFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("callingPoint", IsNullable=true, Order=0)]
        public CallingPoint[] callingPoint {
            get {
                return this.callingPointField;
            }
            set {
                this.callingPointField = value;
                this.RaisePropertyChanged("callingPoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ServiceType serviceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("serviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serviceTypeSpecified {
            get {
                return this.serviceTypeFieldSpecified;
            }
            set {
                this.serviceTypeFieldSpecified = value;
                this.RaisePropertyChanged("serviceTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool serviceChangeRequired {
            get {
                return this.serviceChangeRequiredField;
            }
            set {
                this.serviceChangeRequiredField = value;
                this.RaisePropertyChanged("serviceChangeRequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serviceChangeRequiredSpecified {
            get {
                return this.serviceChangeRequiredFieldSpecified;
            }
            set {
                this.serviceChangeRequiredFieldSpecified = value;
                this.RaisePropertyChanged("serviceChangeRequiredSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool assocIsCancelled {
            get {
                return this.assocIsCancelledField;
            }
            set {
                this.assocIsCancelledField = value;
                this.RaisePropertyChanged("assocIsCancelled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool assocIsCancelledSpecified {
            get {
                return this.assocIsCancelledFieldSpecified;
            }
            set {
                this.assocIsCancelledFieldSpecified = value;
                this.RaisePropertyChanged("assocIsCancelledSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/commontypes")]
    public enum ServiceType {
        
        /// <remarks/>
        train,
        
        /// <remarks/>
        bus,
        
        /// <remarks/>
        ferry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/types")]
    public partial class ServiceDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime generatedAtField;
        
        private ServiceType serviceTypeField;
        
        private string locationNameField;
        
        private string crsField;
        
        private string operatorField;
        
        private string operatorCodeField;
        
        private bool isCancelledField;
        
        private string disruptionReasonField;
        
        private string overdueMessageField;
        
        private string platformField;
        
        private string staField;
        
        private string etaField;
        
        private string ataField;
        
        private string stdField;
        
        private string etdField;
        
        private string atdField;
        
        private string[] adhocAlertsField;
        
        private ArrayOfCallingPoints[] previousCallingPointsField;
        
        private ArrayOfCallingPoints[] subsequentCallingPointsField;
        
        public ServiceDetails() {
            this.isCancelledField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime generatedAt {
            get {
                return this.generatedAtField;
            }
            set {
                this.generatedAtField = value;
                this.RaisePropertyChanged("generatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ServiceType serviceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("serviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
                this.RaisePropertyChanged("locationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string crs {
            get {
                return this.crsField;
            }
            set {
                this.crsField = value;
                this.RaisePropertyChanged("crs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string operatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("operatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isCancelled {
            get {
                return this.isCancelledField;
            }
            set {
                this.isCancelledField = value;
                this.RaisePropertyChanged("isCancelled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string disruptionReason {
            get {
                return this.disruptionReasonField;
            }
            set {
                this.disruptionReasonField = value;
                this.RaisePropertyChanged("disruptionReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string overdueMessage {
            get {
                return this.overdueMessageField;
            }
            set {
                this.overdueMessageField = value;
                this.RaisePropertyChanged("overdueMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
                this.RaisePropertyChanged("platform");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string sta {
            get {
                return this.staField;
            }
            set {
                this.staField = value;
                this.RaisePropertyChanged("sta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string eta {
            get {
                return this.etaField;
            }
            set {
                this.etaField = value;
                this.RaisePropertyChanged("eta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ata {
            get {
                return this.ataField;
            }
            set {
                this.ataField = value;
                this.RaisePropertyChanged("ata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string std {
            get {
                return this.stdField;
            }
            set {
                this.stdField = value;
                this.RaisePropertyChanged("std");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string etd {
            get {
                return this.etdField;
            }
            set {
                this.etdField = value;
                this.RaisePropertyChanged("etd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string atd {
            get {
                return this.atdField;
            }
            set {
                this.atdField = value;
                this.RaisePropertyChanged("atd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute("adhocAlertText", Namespace="http://thalesgroup.com/RTTI/2012-01-13/ldb/types")]
        public string[] adhocAlerts {
            get {
                return this.adhocAlertsField;
            }
            set {
                this.adhocAlertsField = value;
                this.RaisePropertyChanged("adhocAlerts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("callingPointList")]
        public ArrayOfCallingPoints[] previousCallingPoints {
            get {
                return this.previousCallingPointsField;
            }
            set {
                this.previousCallingPointsField = value;
                this.RaisePropertyChanged("previousCallingPoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        [System.Xml.Serialization.XmlArrayItemAttribute("callingPointList")]
        public ArrayOfCallingPoints[] subsequentCallingPoints {
            get {
                return this.subsequentCallingPointsField;
            }
            set {
                this.subsequentCallingPointsField = value;
                this.RaisePropertyChanged("subsequentCallingPoints");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/types")]
    public partial class ServiceLocation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string locationNameField;
        
        private string crsField;
        
        private string viaField;
        
        private string futureChangeToField;
        
        private bool assocIsCancelledField;
        
        public ServiceLocation() {
            this.assocIsCancelledField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
                this.RaisePropertyChanged("locationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string crs {
            get {
                return this.crsField;
            }
            set {
                this.crsField = value;
                this.RaisePropertyChanged("crs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string via {
            get {
                return this.viaField;
            }
            set {
                this.viaField = value;
                this.RaisePropertyChanged("via");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string futureChangeTo {
            get {
                return this.futureChangeToField;
            }
            set {
                this.futureChangeToField = value;
                this.RaisePropertyChanged("futureChangeTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool assocIsCancelled {
            get {
                return this.assocIsCancelledField;
            }
            set {
                this.assocIsCancelledField = value;
                this.RaisePropertyChanged("assocIsCancelled");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/types")]
    public partial class ServiceItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceLocation[] originField;
        
        private ServiceLocation[] destinationField;
        
        private ServiceLocation[] currentOriginsField;
        
        private ServiceLocation[] currentDestinationsField;
        
        private string staField;
        
        private string etaField;
        
        private string stdField;
        
        private string etdField;
        
        private string platformField;
        
        private string operatorField;
        
        private string operatorCodeField;
        
        private bool isCircularRouteField;
        
        private string serviceIDField;
        
        private string[] adhocAlertsField;
        
        public ServiceItem() {
            this.isCircularRouteField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("location")]
        public ServiceLocation[] origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
                this.RaisePropertyChanged("origin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("location")]
        public ServiceLocation[] destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("location")]
        public ServiceLocation[] currentOrigins {
            get {
                return this.currentOriginsField;
            }
            set {
                this.currentOriginsField = value;
                this.RaisePropertyChanged("currentOrigins");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("location")]
        public ServiceLocation[] currentDestinations {
            get {
                return this.currentDestinationsField;
            }
            set {
                this.currentDestinationsField = value;
                this.RaisePropertyChanged("currentDestinations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sta {
            get {
                return this.staField;
            }
            set {
                this.staField = value;
                this.RaisePropertyChanged("sta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string eta {
            get {
                return this.etaField;
            }
            set {
                this.etaField = value;
                this.RaisePropertyChanged("eta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string std {
            get {
                return this.stdField;
            }
            set {
                this.stdField = value;
                this.RaisePropertyChanged("std");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string etd {
            get {
                return this.etdField;
            }
            set {
                this.etdField = value;
                this.RaisePropertyChanged("etd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
                this.RaisePropertyChanged("platform");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string operatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("operatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isCircularRoute {
            get {
                return this.isCircularRouteField;
            }
            set {
                this.isCircularRouteField = value;
                this.RaisePropertyChanged("isCircularRoute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string serviceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
                this.RaisePropertyChanged("serviceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("adhocAlertText", Namespace="http://thalesgroup.com/RTTI/2012-01-13/ldb/types")]
        public string[] adhocAlerts {
            get {
                return this.adhocAlertsField;
            }
            set {
                this.adhocAlertsField = value;
                this.RaisePropertyChanged("adhocAlerts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2012-01-13/ldb/types")]
    public partial class NRCCMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/types")]
    public partial class StationBoard : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime generatedAtField;
        
        private string locationNameField;
        
        private string crsField;
        
        private string filterLocationNameField;
        
        private string filtercrsField;
        
        private FilterType filterTypeField;
        
        private NRCCMessage[] nrccMessagesField;
        
        private bool platformAvailableField;
        
        private bool areServicesAvailableField;
        
        private ServiceItem[] trainServicesField;
        
        private ServiceItem[] busServicesField;
        
        private ServiceItem[] ferryServicesField;
        
        public StationBoard() {
            this.filterTypeField = FilterType.to;
            this.platformAvailableField = false;
            this.areServicesAvailableField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime generatedAt {
            get {
                return this.generatedAtField;
            }
            set {
                this.generatedAtField = value;
                this.RaisePropertyChanged("generatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
                this.RaisePropertyChanged("locationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string crs {
            get {
                return this.crsField;
            }
            set {
                this.crsField = value;
                this.RaisePropertyChanged("crs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string filterLocationName {
            get {
                return this.filterLocationNameField;
            }
            set {
                this.filterLocationNameField = value;
                this.RaisePropertyChanged("filterLocationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string filtercrs {
            get {
                return this.filtercrsField;
            }
            set {
                this.filtercrsField = value;
                this.RaisePropertyChanged("filtercrs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DefaultValueAttribute(FilterType.to)]
        public FilterType filterType {
            get {
                return this.filterTypeField;
            }
            set {
                this.filterTypeField = value;
                this.RaisePropertyChanged("filterType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://thalesgroup.com/RTTI/2012-01-13/ldb/types")]
        public NRCCMessage[] nrccMessages {
            get {
                return this.nrccMessagesField;
            }
            set {
                this.nrccMessagesField = value;
                this.RaisePropertyChanged("nrccMessages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool platformAvailable {
            get {
                return this.platformAvailableField;
            }
            set {
                this.platformAvailableField = value;
                this.RaisePropertyChanged("platformAvailable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool areServicesAvailable {
            get {
                return this.areServicesAvailableField;
            }
            set {
                this.areServicesAvailableField = value;
                this.RaisePropertyChanged("areServicesAvailable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("service")]
        public ServiceItem[] trainServices {
            get {
                return this.trainServicesField;
            }
            set {
                this.trainServicesField = value;
                this.RaisePropertyChanged("trainServices");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("service")]
        public ServiceItem[] busServices {
            get {
                return this.busServicesField;
            }
            set {
                this.busServicesField = value;
                this.RaisePropertyChanged("busServices");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("service")]
        public ServiceItem[] ferryServices {
            get {
                return this.ferryServicesField;
            }
            set {
                this.ferryServicesField = value;
                this.RaisePropertyChanged("ferryServices");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/commontypes")]
    public enum FilterType {
        
        /// <remarks/>
        to,
        
        /// <remarks/>
        from,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDepartureBoardRequest", WrapperNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", IsWrapped=true)]
    public partial class GetDepartureBoardRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://thalesgroup.com/RTTI/2013-11-28/Token/types")]
        public TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=0)]
        public ushort numRows;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=1)]
        public string crs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=2)]
        public string filterCrs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=3)]
        [System.ComponentModel.DefaultValueAttribute(FilterType.to)]
        public TrainNotifier.IIS.WebApi.OpenLDBWS.FilterType filterType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=4)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int timeOffset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=5)]
        [System.ComponentModel.DefaultValueAttribute(120)]
        public int timeWindow;
        
        public GetDepartureBoardRequest() {
        }
        
        public GetDepartureBoardRequest(TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken, ushort numRows, string crs, string filterCrs, TrainNotifier.IIS.WebApi.OpenLDBWS.FilterType filterType, int timeOffset, int timeWindow) {
            this.AccessToken = AccessToken;
            this.numRows = numRows;
            this.crs = crs;
            this.filterCrs = filterCrs;
            this.filterType = filterType;
            this.timeOffset = timeOffset;
            this.timeWindow = timeWindow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDepartureBoardResponse", WrapperNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", IsWrapped=true)]
    public partial class GetDepartureBoardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=0)]
        public TrainNotifier.IIS.WebApi.OpenLDBWS.StationBoard GetStationBoardResult;
        
        public GetDepartureBoardResponse() {
        }
        
        public GetDepartureBoardResponse(TrainNotifier.IIS.WebApi.OpenLDBWS.StationBoard GetStationBoardResult) {
            this.GetStationBoardResult = GetStationBoardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArrivalBoardRequest", WrapperNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", IsWrapped=true)]
    public partial class GetArrivalBoardRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://thalesgroup.com/RTTI/2013-11-28/Token/types")]
        public TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=0)]
        public ushort numRows;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=1)]
        public string crs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=2)]
        public string filterCrs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=3)]
        [System.ComponentModel.DefaultValueAttribute(FilterType.to)]
        public TrainNotifier.IIS.WebApi.OpenLDBWS.FilterType filterType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=4)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int timeOffset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=5)]
        [System.ComponentModel.DefaultValueAttribute(120)]
        public int timeWindow;
        
        public GetArrivalBoardRequest() {
        }
        
        public GetArrivalBoardRequest(TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken, ushort numRows, string crs, string filterCrs, TrainNotifier.IIS.WebApi.OpenLDBWS.FilterType filterType, int timeOffset, int timeWindow) {
            this.AccessToken = AccessToken;
            this.numRows = numRows;
            this.crs = crs;
            this.filterCrs = filterCrs;
            this.filterType = filterType;
            this.timeOffset = timeOffset;
            this.timeWindow = timeWindow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArrivalBoardResponse", WrapperNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", IsWrapped=true)]
    public partial class GetArrivalBoardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=0)]
        public TrainNotifier.IIS.WebApi.OpenLDBWS.StationBoard GetStationBoardResult;
        
        public GetArrivalBoardResponse() {
        }
        
        public GetArrivalBoardResponse(TrainNotifier.IIS.WebApi.OpenLDBWS.StationBoard GetStationBoardResult) {
            this.GetStationBoardResult = GetStationBoardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArrivalDepartureBoardRequest", WrapperNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", IsWrapped=true)]
    public partial class GetArrivalDepartureBoardRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://thalesgroup.com/RTTI/2013-11-28/Token/types")]
        public TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=0)]
        public ushort numRows;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=1)]
        public string crs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=2)]
        public string filterCrs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=3)]
        [System.ComponentModel.DefaultValueAttribute(FilterType.to)]
        public TrainNotifier.IIS.WebApi.OpenLDBWS.FilterType filterType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=4)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int timeOffset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=5)]
        [System.ComponentModel.DefaultValueAttribute(120)]
        public int timeWindow;
        
        public GetArrivalDepartureBoardRequest() {
        }
        
        public GetArrivalDepartureBoardRequest(TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken, ushort numRows, string crs, string filterCrs, TrainNotifier.IIS.WebApi.OpenLDBWS.FilterType filterType, int timeOffset, int timeWindow) {
            this.AccessToken = AccessToken;
            this.numRows = numRows;
            this.crs = crs;
            this.filterCrs = filterCrs;
            this.filterType = filterType;
            this.timeOffset = timeOffset;
            this.timeWindow = timeWindow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArrivalDepartureBoardResponse", WrapperNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", IsWrapped=true)]
    public partial class GetArrivalDepartureBoardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=0)]
        public TrainNotifier.IIS.WebApi.OpenLDBWS.StationBoard GetStationBoardResult;
        
        public GetArrivalDepartureBoardResponse() {
        }
        
        public GetArrivalDepartureBoardResponse(TrainNotifier.IIS.WebApi.OpenLDBWS.StationBoard GetStationBoardResult) {
            this.GetStationBoardResult = GetStationBoardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceDetailsRequest", WrapperNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", IsWrapped=true)]
    public partial class GetServiceDetailsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://thalesgroup.com/RTTI/2013-11-28/Token/types")]
        public TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=0)]
        public string serviceID;
        
        public GetServiceDetailsRequest() {
        }
        
        public GetServiceDetailsRequest(TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken, string serviceID) {
            this.AccessToken = AccessToken;
            this.serviceID = serviceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceDetailsResponse", WrapperNamespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", IsWrapped=true)]
    public partial class GetServiceDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2014-02-20/ldb/", Order=0)]
        public TrainNotifier.IIS.WebApi.OpenLDBWS.ServiceDetails GetServiceDetailsResult;
        
        public GetServiceDetailsResponse() {
        }
        
        public GetServiceDetailsResponse(TrainNotifier.IIS.WebApi.OpenLDBWS.ServiceDetails GetServiceDetailsResult) {
            this.GetServiceDetailsResult = GetServiceDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LDBServiceSoapChannel : TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LDBServiceSoapClient : System.ServiceModel.ClientBase<TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap>, TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap {
        
        public LDBServiceSoapClient() {
        }
        
        public LDBServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LDBServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LDBServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LDBServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainNotifier.IIS.WebApi.OpenLDBWS.GetDepartureBoardResponse TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap.GetDepartureBoard(TrainNotifier.IIS.WebApi.OpenLDBWS.GetDepartureBoardRequest request) {
            return base.Channel.GetDepartureBoard(request);
        }
        
        public TrainNotifier.IIS.WebApi.OpenLDBWS.StationBoard GetDepartureBoard(TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken, ushort numRows, string crs, string filterCrs, TrainNotifier.IIS.WebApi.OpenLDBWS.FilterType filterType, int timeOffset, int timeWindow) {
            TrainNotifier.IIS.WebApi.OpenLDBWS.GetDepartureBoardRequest inValue = new TrainNotifier.IIS.WebApi.OpenLDBWS.GetDepartureBoardRequest();
            inValue.AccessToken = AccessToken;
            inValue.numRows = numRows;
            inValue.crs = crs;
            inValue.filterCrs = filterCrs;
            inValue.filterType = filterType;
            inValue.timeOffset = timeOffset;
            inValue.timeWindow = timeWindow;
            TrainNotifier.IIS.WebApi.OpenLDBWS.GetDepartureBoardResponse retVal = ((TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap)(this)).GetDepartureBoard(inValue);
            return retVal.GetStationBoardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainNotifier.IIS.WebApi.OpenLDBWS.GetDepartureBoardResponse> TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap.GetDepartureBoardAsync(TrainNotifier.IIS.WebApi.OpenLDBWS.GetDepartureBoardRequest request) {
            return base.Channel.GetDepartureBoardAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainNotifier.IIS.WebApi.OpenLDBWS.GetDepartureBoardResponse> GetDepartureBoardAsync(TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken, ushort numRows, string crs, string filterCrs, TrainNotifier.IIS.WebApi.OpenLDBWS.FilterType filterType, int timeOffset, int timeWindow) {
            TrainNotifier.IIS.WebApi.OpenLDBWS.GetDepartureBoardRequest inValue = new TrainNotifier.IIS.WebApi.OpenLDBWS.GetDepartureBoardRequest();
            inValue.AccessToken = AccessToken;
            inValue.numRows = numRows;
            inValue.crs = crs;
            inValue.filterCrs = filterCrs;
            inValue.filterType = filterType;
            inValue.timeOffset = timeOffset;
            inValue.timeWindow = timeWindow;
            return ((TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap)(this)).GetDepartureBoardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalBoardResponse TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap.GetArrivalBoard(TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalBoardRequest request) {
            return base.Channel.GetArrivalBoard(request);
        }
        
        public TrainNotifier.IIS.WebApi.OpenLDBWS.StationBoard GetArrivalBoard(TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken, ushort numRows, string crs, string filterCrs, TrainNotifier.IIS.WebApi.OpenLDBWS.FilterType filterType, int timeOffset, int timeWindow) {
            TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalBoardRequest inValue = new TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalBoardRequest();
            inValue.AccessToken = AccessToken;
            inValue.numRows = numRows;
            inValue.crs = crs;
            inValue.filterCrs = filterCrs;
            inValue.filterType = filterType;
            inValue.timeOffset = timeOffset;
            inValue.timeWindow = timeWindow;
            TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalBoardResponse retVal = ((TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap)(this)).GetArrivalBoard(inValue);
            return retVal.GetStationBoardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalBoardResponse> TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap.GetArrivalBoardAsync(TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalBoardRequest request) {
            return base.Channel.GetArrivalBoardAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalBoardResponse> GetArrivalBoardAsync(TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken, ushort numRows, string crs, string filterCrs, TrainNotifier.IIS.WebApi.OpenLDBWS.FilterType filterType, int timeOffset, int timeWindow) {
            TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalBoardRequest inValue = new TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalBoardRequest();
            inValue.AccessToken = AccessToken;
            inValue.numRows = numRows;
            inValue.crs = crs;
            inValue.filterCrs = filterCrs;
            inValue.filterType = filterType;
            inValue.timeOffset = timeOffset;
            inValue.timeWindow = timeWindow;
            return ((TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap)(this)).GetArrivalBoardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalDepartureBoardResponse TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap.GetArrivalDepartureBoard(TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalDepartureBoardRequest request) {
            return base.Channel.GetArrivalDepartureBoard(request);
        }
        
        public TrainNotifier.IIS.WebApi.OpenLDBWS.StationBoard GetArrivalDepartureBoard(TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken, ushort numRows, string crs, string filterCrs, TrainNotifier.IIS.WebApi.OpenLDBWS.FilterType filterType, int timeOffset, int timeWindow) {
            TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalDepartureBoardRequest inValue = new TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalDepartureBoardRequest();
            inValue.AccessToken = AccessToken;
            inValue.numRows = numRows;
            inValue.crs = crs;
            inValue.filterCrs = filterCrs;
            inValue.filterType = filterType;
            inValue.timeOffset = timeOffset;
            inValue.timeWindow = timeWindow;
            TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalDepartureBoardResponse retVal = ((TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap)(this)).GetArrivalDepartureBoard(inValue);
            return retVal.GetStationBoardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalDepartureBoardResponse> TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap.GetArrivalDepartureBoardAsync(TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalDepartureBoardRequest request) {
            return base.Channel.GetArrivalDepartureBoardAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalDepartureBoardResponse> GetArrivalDepartureBoardAsync(TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken, ushort numRows, string crs, string filterCrs, TrainNotifier.IIS.WebApi.OpenLDBWS.FilterType filterType, int timeOffset, int timeWindow) {
            TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalDepartureBoardRequest inValue = new TrainNotifier.IIS.WebApi.OpenLDBWS.GetArrivalDepartureBoardRequest();
            inValue.AccessToken = AccessToken;
            inValue.numRows = numRows;
            inValue.crs = crs;
            inValue.filterCrs = filterCrs;
            inValue.filterType = filterType;
            inValue.timeOffset = timeOffset;
            inValue.timeWindow = timeWindow;
            return ((TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap)(this)).GetArrivalDepartureBoardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainNotifier.IIS.WebApi.OpenLDBWS.GetServiceDetailsResponse TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap.GetServiceDetails(TrainNotifier.IIS.WebApi.OpenLDBWS.GetServiceDetailsRequest request) {
            return base.Channel.GetServiceDetails(request);
        }
        
        public TrainNotifier.IIS.WebApi.OpenLDBWS.ServiceDetails GetServiceDetails(TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken, string serviceID) {
            TrainNotifier.IIS.WebApi.OpenLDBWS.GetServiceDetailsRequest inValue = new TrainNotifier.IIS.WebApi.OpenLDBWS.GetServiceDetailsRequest();
            inValue.AccessToken = AccessToken;
            inValue.serviceID = serviceID;
            TrainNotifier.IIS.WebApi.OpenLDBWS.GetServiceDetailsResponse retVal = ((TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap)(this)).GetServiceDetails(inValue);
            return retVal.GetServiceDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainNotifier.IIS.WebApi.OpenLDBWS.GetServiceDetailsResponse> TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap.GetServiceDetailsAsync(TrainNotifier.IIS.WebApi.OpenLDBWS.GetServiceDetailsRequest request) {
            return base.Channel.GetServiceDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainNotifier.IIS.WebApi.OpenLDBWS.GetServiceDetailsResponse> GetServiceDetailsAsync(TrainNotifier.IIS.WebApi.OpenLDBWS.AccessToken AccessToken, string serviceID) {
            TrainNotifier.IIS.WebApi.OpenLDBWS.GetServiceDetailsRequest inValue = new TrainNotifier.IIS.WebApi.OpenLDBWS.GetServiceDetailsRequest();
            inValue.AccessToken = AccessToken;
            inValue.serviceID = serviceID;
            return ((TrainNotifier.IIS.WebApi.OpenLDBWS.LDBServiceSoap)(this)).GetServiceDetailsAsync(inValue);
        }
    }
}
